import type { Metadata } from "next";
import { Providers } from "./providers";
import { ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <ToastContainer />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
